### PR TITLE
add test strategy script for bulk testing

### PR DESCRIPTION
**Pull request by kakulukia**
added requirements.txt and icecream for nice print statements
added local test script to be able to run multiple test on symbols and time frames at once and find the best one according to a chosen metric value.

All you need to:
. import your strategy
. be sure to import all needed candles
. (un)comment, add, change symbols and time frames as needed

!!! https://github.com/jesse-ai/jesse/pull/435 is a requirement for this test script

The script will output the backtest metrics and the charts filename (in a good terminal you can just CMD+click on it to open the chart). After all single backtests are done there will be an additional statistic for all medium values for each time frame. So for the default it will look like this:

image

### CODE REVIEW

**Comment by yakir4123** [comment]
maybe you can just create a gist for that and ask Saleh to add it to awesome-jesse, it doesn't seems fit to this repo.

**Comment by kakulukia** [comment]
My thought was: It helps testing the developed strategy and thus would be handy to have right at your fingertips as well as maybe a template for a Jupyter notebook with a good TradingView integration.

What - in your eyes - is the stuff that should be in this repo instead? 

From my point of view, I was missing such a command line testing possibility as i like setting breakpoints and and customise or test out a few things while the strategy is running. Jesse offers this research module, but no "put your strategy here and press go" option yet this kind of testing. And that was my reason for opening this PR.
It can surely also be a gist, tho.

**Comment by btagliani** [comment]
@kakulukia Hey! nice work. Im maintaining a fork of jesse-bulk in my repo, its working at the moment. Its something similiar to this but also ranks the best strategies after a simulation, and refines them based on your config. Maybe check it out, if you have any questions ping me. I would also love to integrate it to Jesse but I think I would like to add it to the GUI. Maybe after the new dashboard is released by @saleh-mir I can integrate it. Check it out at https://github.com/btagliani/jesse-bulk
Also this is needed for jesse-bulk to run properly https://github.com/jesse-ai/jesse/pull/413

**Comment by kakulukia** [comment]
Interesting! With you being the maintainer - does that mean that @cryptocoinserver is officially not active any longer? I tried to contact him because of another question with an indicator he wrote.

I remember seeing that project in the awesome list, but as it mentioned the dashboard i was putting it aside having misread that somehow as just is for the dashboard version - at that time i didnt know there was a command line version of Jesse.

Seems i fixed one of the original warnings "warm-up-candles are taken from the candles passed. So the actual start_date is different then it would be during a normal backtest." :) You can comment on https://github.com/jesse-ai/jesse/pull/435 to fix it for everybody. :)

I will have another look at jesse-bulk.

**Comment by saleh-mir** [comment]
This is pretty cool, but as mentioned by others, it is not a fit for this repository. It can be great if you created your own repository for it and then submitted the PR for the awesome-jesse repository to mention it there. Also, I will definitely add a bulk backtesting feature like this, maybe even using your own code so users can use this within the dashboard as well.

**Pull request closed without merging**
